name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd server
        npm install
        cd ../movifrontend
        npm install
        cd ..

    - name: Build frontend
      run: |
        cd movifrontend
        npm run build
        cd ..

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/450ProjectProd
          git restore .
          git pull develop main
          cd server
          npm install
          cd ../movifrontend
          npm install
          npm run build
          cd ..
          pm2 restart all
